[package]
name = "lostark-status-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "3.1", features = ["derive"] }
notify-rust = "4.5"
scraper = "0.12"
ureq = "2.3"
